version: '3.8'

services:
  api:
    build: .
    ports:
      - "5600:5600"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
